version: '2'
services:
    web:
        build: .
        ports:
        - "5000:5000"
        volumes:
        - .:/go/src/github.com/mecusorin/SampleGoRedisDockerNginx/main
        depends_on:
        - redis
    redis:
        image: redis
